logging:
  level:
    org.springframework.security: DEBUG
spring:
  security:
    user:
      roles: USER,ADMIN
  session:
    store-type: redis
  web:
    resources:
      static-locations: classpath:/static/browser/
server:
  port: 8082
