spring:
  aop:
    proxy-target-class: true
  web:
    resources:
      static-locations: classpath:/static/browser/
  security:
    oauth2:
      client:
        registration:
          acme:
            client-id: acme
            client-secret: acmesecret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          acme:
            authorization-uri: http://localhost:9999/oauth2/authorize
            token-uri: http://localhost:9999/oauth2/token
            jwk-set-uri: http://localhost:9999/oauth2/jwks
            user-info-uri: http://localhost:9999/userinfo
  cloud:
    gateway:
      routes:
        - id: resource
          uri: http://localhost:9000
          predicates:
            - Path=/resource/**
        - id: user
          uri: http://localhost:9999
          predicates:
            - Path=/user/**

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
